import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { templatesPart1 } from './templates_part1.mjs';
import { templatesPart2 } from './templates_part2.mjs';
import { templatesPart3 } from './templates_part3.mjs';
import { templatesPart4 } from './templates_part4.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const targetPath = path.resolve(__dirname, '../../src/data/legalTemplates.ts');

const allTemplates = [
  ...templatesPart1,
  ...templatesPart2,
  ...templatesPart3,
  ...templatesPart4
];

console.log(`Aggregating ${allTemplates.length} templates...`);

let tsCode = `// Autogenerated authentic legal templates for AdvokatAI
// Powered by 3-layer legal document architecture
import {
  LegalDocumentModel,
  cleanField,
  formatMoney,
  formatUzbekDate,
  renderToPlainText
} from '../utils/documentRenderer';

export interface Field {
  key: string;
  label: string;
  type: 'text' | 'date' | 'number' | 'select' | 'textarea';
  placeholder?: string;
  required?: boolean;
  helper?: string;
  options?: string[];
}

export interface LegalTemplate {
  id: number;
  name: string;
  icon: string;
  category: string;
  desc?: string;
  legalBasis?: string;
  disclaimer?: string;
  fields: Field[];
  generateModel: (data: Record<string, any>) => LegalDocumentModel;
  generate: (data: Record<string, any>) => string;
}

export const TEMPLATE_CATEGORIES = [
  'Barchasi',
  'Ijara va ko‘chmas mulk',
  'Mehnat hujjatlari',
  'Umumiy arizalar',
  'Sud hujjatlari',
  'Qarzdorlik va pul',
  'Shartnomalar',
  'Ishonchnoma va vakolat',
  'Avtomobil',
  'Oila va fuqarolik',
  'Tadbirkorlik'
];

export const legalTemplatesDatabase: LegalTemplate[] = [
`;

for (let i = 0; i < allTemplates.length; i++) {
  const t = allTemplates[i];
  tsCode += `  {\n`;
  tsCode += `    id: ${t.id},\n`;
  tsCode += `    name: ${JSON.stringify(t.name)},\n`;
  tsCode += `    icon: ${JSON.stringify(t.icon)},\n`;
  tsCode += `    category: ${JSON.stringify(t.category)},\n`;
  tsCode += `    desc: ${JSON.stringify(t.desc || '')},\n`;
  tsCode += `    legalBasis: ${JSON.stringify(t.legalBasis || '')},\n`;
  tsCode += `    disclaimer: ${JSON.stringify(t.disclaimer || '')},\n`;
  tsCode += `    fields: ${JSON.stringify(t.fields, null, 6)},\n`;
  tsCode += `    generateModel: ${t.codeBody},\n`;
  tsCode += `    generate(data: Record<string, any>) {\n`;
  tsCode += `      return renderToPlainText(this.generateModel(data));\n`;
  tsCode += `    }\n`;
  tsCode += `  }${i < allTemplates.length - 1 ? ',' : ''}\n`;
}

tsCode += `];\n`;

fs.writeFileSync(targetPath, tsCode, 'utf8');
console.log(`Successfully generated ${allTemplates.length} templates in ${targetPath}`);
